# Generated by Django 4.1.5 on 2023-02-26 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_tenant_managers_tenant_address_tenant_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 26, 16, 56, 38, 744627)),
        ),
    ]
