# Generated by Django 4.1.5 on 2023-02-28 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_alter_tenant_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='fcm_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 9, 57, 14, 649777)),
        ),
    ]
