# Generated by Django 4.1.5 on 2023-02-28 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_alter_tenant_fcm_token_alter_tenant_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 9, 58, 46, 115738)),
        ),
    ]
