# Generated by Django 4.1.5 on 2023-03-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.TextField(choices=[('BAISAKH', 'Baisakh'), ('JESTHA', 'Jestha'), ('ASHAR', 'Ashar'), ('SHRAWAN', 'Swrawan'), ('BHADRA', 'Bhadra'), ('ASHWIN', 'Ashwin'), ('KARTIK', 'Kartik'), ('MANGSHIR', 'Mangshir'), ('POUSH', 'Poush'), ('MAGH', 'Magh'), ('FALGUN', 'Falgun'), ('CHAITRA', 'Chaitra')]),
        ),
    ]
