# Generated by Django 4.1.5 on 2023-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='payment',
            name='room_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
