# Generated by Django 4.1.5 on 2023-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
