# Generated by Django 4.1.5 on 2023-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
