# Generated by Django 4.1.5 on 2023-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
