# Generated by Django 4.1.5 on 2023-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='username',
        ),
    ]
