# Generated by Django 4.1.5 on 2023-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('owner', '0003_rename_name_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, related_name='owners', related_query_name='owner', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', null=True, related_name='owners_permissions', related_query_name='owner_permissions', to='auth.permission'),
        ),
    ]
