# Generated by Django 4.1.5 on 2023-02-18 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_owner_groups_alter_owner_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 18, 8, 31, 45, 442229, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
