# Generated by Django 4.1.5 on 2023-02-20 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_owner_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='joined',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 23, 21, 35, 807388)),
        ),
    ]
