# Generated by Django 4.1.5 on 2023-02-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_owner_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='joined',
        ),
    ]
