# Generated by Django 4.1.5 on 2023-03-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tenant',
        ),
        migrations.AddField(
            model_name='bill',
            name='room_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
