# Generated by Django 4.1.5 on 2023-03-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_bill_tenant_bill_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
