# Generated by Django 4.1.5 on 2023-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
