# Generated by Django 4.1.5 on 2023-04-10 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2023, 4, 10, 15, 27, 31, 674348, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
