version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: sh -c "python manage.py makemigrations; python manage.py migrate; echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@gmail.com', 'admin')\" | python manage.py shell; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
